### ISSUE TITLE
Can't resize icons.

### ISSUE THREAD

**Issue by mrbrianng** [patcheung/Font-Awesome-OmniGraffle-Stencil#3]
Any plans to make the icons re-sizeable in Omnigraffle?

**Comment by patcheung** [comment]
They are resizable. Since the icons are actual fonts in the stencil...you resize them by using font sizing.  For ease, I just select object and use Command and + or - to change size quickly.

**Comment by mrbrianng** [comment]
Brilliant... thank you!
